on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check and Lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cargo check
        run: cargo check --workspace --all-targets
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --workspace
